### PR TITLE
example for image

### PR DESCRIPTION
**Pull request by mango314**
In response to Issue https://github.com/evancz/elm-graphics/issues/9 I added a 2 lines concerning how to use `image` and `fittedImage`

### CODE REVIEW

**Comment by jvoigtlaender** [comment]
The example for fittedImage is not type-correct.

**Comment by mango314** [comment]
thanks @jvoigtlaender 

the type is `Int -> Int -> String -> Element` 

so the example will read `fittedImage 100 100 "yogi.jpg"`

it should be correct now

**Comment by mango314** [comment]
Hello @jvoigtlaender there's no problem with this pull request, right?

**Comment by jvoigtlaender** [comment]
Yes, you are correct. There is no problem with this pull request.

**Pull request merged**
